<?php

$tasks =
    [
        'Please Pull before start working...',
        '----filename has been moved from base table to translation and (view, controller, migration model, seeder, and commands has been updated successfully).',
        '----Exam seeder has been created.',
        '----Course duration is set to months but what about pen drive courses? there should be a selection for hours only for pen-drive courses',
        '----slug input field not available in Test Series module.',
        '----URLs are using "id" after all the menus from student zone menu please use "slug" in urls.',
        '----Check all images should be "object-fit" if possible.',
        '----Also update duration in course seeder. Currently measured in month ( must be measured in hours also).',
        '----Job vacancies dizvik tech. is not complete',
        '----Do something about installment_duration.',
        '----In Admin panel add active class in sidebar dropdown.',
        '----*After all the route configured in Front Desktop menu also configure Off-canvas menu in Front nav.blade.php',
        '----resources/views/front/download-detail.blade.php on line=13 | Attempt to read property "category_name" on null',
        '----Eorrors in Class_Notes_donload.seed_class_notes() & ncert_download.seed_ncert()',
        '----add laravel settings from spatie',
        '----dynamic sidebar',
        '----Dhyeya Gallery Module',
        '----Home notification panel has no anchor( links )',
        '----Yotube channel integration',
        '----Dhyeya Store integration',
        'Add topper batch for Achiever and remove toppers module',
        'multi language button fix',
        'create an Excel file having column(dhyeya sides urls, and owr.',
        'Menu and footer integration',
        'Create 404 page',
        '----Make Gallery image Seeder',
        '----Change downloads page ui',
        '----Paginate downloads page',
        '----Please Delete menu Add/Remove toggle button from all the modules in admin panel',
        '----Add users module in admin panel',
        'Review breadcrumb on front end',
        '----Revision on single post page front design',
        'Course module is not working properly, course mode and course type  fixing',
        'Whatsapp chat integration on web and mobile end',
        'Mention all our YT Channel name with their objectives, then a showcase of highlighted top videos scrolling automatically in right side pane',
        'Vector images to be more professional.',
        'Give a whole sitemap and maximum links of internal pages for SEO purpose.',
        'Upse Faqs static page skipped lang support',
    ];
